#!/usr/bin/env python3

"""Get the list od arginine CD-NE-CZ-NH1 dihedral angles
of a protein specified on the command line. Only processes
the first model in PDB files with multiple models.

Urage: arg-dih <inputPDBfile>
"""

from Bio.PDB import *
from sys import argv
import math

#load the PDB file...
if len(argv) == 1 :  #no arguments specified
	print("No input pdb file specified!")
	exit(1)
filename = argv[1]

structure = PDBParser(QUIET = True).get_structure("A", filename)
models = list(structure.get_models())[0]
residues = [i for i in models.get_residues() if i.get_resname() == "ARG"]
print(f"This structure has {len(models)} models.")
for arg in residues:
	try:
		atom_vectors = [arg[i].get_vector() for i in ["CD", "NE", "CZ", "NH1"]]
		dih = calc_dihedral(*atom_vectors)
		print(f"{arg}, {arg.get_parent().get_id()} : {dih*180/3.14:>5.2f}")
	except:
		continue
